#!/usr/bin/env python3
"""Serve this folder with a http server and open it in a browser."""

import http.server
import signal
import subprocess
import sys

PORT = 8765


class CustomHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
    """Wrapper class to customize the http server."""

    def log_message(self, format, *args):
        """Colorized log."""
        ansi_blue = "\033[0;34m"
        ansi_cyan = "\033[0;36m"
        ansi_green = "\033[0;32m"
        ansi_white = "\033[0;37m"
        ansi_red = "\033[0;31m"

        if format == '"%s" %s %s':
            http_action = args[0]
            http_code = args[1]
            http_size = args[2]

            # Highlight http 4xx client and 5xx server errors.
            if http_code.startswith(("4", "5")):
                ansi_status = ansi_red
            else:
                ansi_status = ansi_green

            msg = f'{ansi_status}"{http_action}" {http_code} {ansi_white}{http_size}'

        elif format == "code %d, message %s":
            err_code = args[0]
            err_msg = args[1]
            msg = f"{ansi_red}code {err_code}, message '{err_msg}'"

        print(
            f"{ansi_blue}{self.address_string()} - -",
            f"{ansi_cyan}[{self.log_date_time_string()}]",
            msg,
        )


# Handle ctrl-c signal to exit cleanly.
signal.signal(signal.SIGINT, lambda signum, frame: (signum, frame) and sys.exit(0))

# Open web browser
subprocess.run(f"open http://127.0.0.1:{PORT}", shell=True)

# Start web server
server_address = ("localhost", PORT)
httpd = http.server.ThreadingHTTPServer(server_address, CustomHTTPRequestHandler)
httpd.serve_forever()
